### ISSUE TITLE
How to get a system.xml file?

### ISSUE THREAD

**Issue by benfre** [toptica/python-lasersdk#2]
The function `lasersdk_gen.download_system_xml` shows to get a  `system.xml` from a web server. And the comment says "Downloads a DeCoP system model from a device." 

Which device serves the http files? How can we download this file? 

We want this file because it seems throgh this file we can get the parameter list and communicating with DLC from other programing language easier.

**Comment by a1rw4lk** [comment]
Hi benfre, 
as you already pointed out, the function `lasersdk_gen.download_system_xml` is used to download a DeCoP system model from the device. On several products of TOPTICA this functionality is necessary, since the DeCoP system model is not static. Therefore the device provides a Web Server to download this file. 

For the DLCpro however you **do not need** this functionality. The DeCoP system model `system.xml` is static and is also included in the source code of the python-lasersdk package. 

If you want to have a complete parameter list you can refer to the **documentation** we provide with every system. There you will find a *.pdf document by the name of `DLCpro-Command-Reference.pdf` which lists all parameters, their access level, their description and a general guide on how to communicate with the DLCpro. 
If you cannot find the documentation we provided, you can download the [latest software package](https://www.toptica.com/fileadmin/Editors_English/03_products/03_tunable_diode_lasers/04_control_electronics/01_laser_driving_electronics/01_DLC_pro/DLCpro_v2.2.0.zip ) which includes the documentation on our [website](https://www.toptica.com/products/tunable-diode-lasers/laser-driving-electronics/dlc-pro/#c2326). 

Let me know if there is anything else you need. 

Have a pleasant day!
Your TOPTICA Team

**Comment by benfre** [comment]
Thanks. I will look into the document. 
But it will be a bit inconvenient. When I am writing c++ interface to DLCpro, I need mannually write the parameters list and commands list in the source file. I hope maybe  the `system.xml`  can be packaged in the python whl file, so I can generate the model from that file.
